/*
 * Generated by Bluespec Compiler, version 2012.10.beta2 (build 29674, 2012-10.10)
 * 
 * On Wed Apr 17 15:19:32 EDT 2013
 * 
 */
extern "C" {
  void bluenoc_close_tcp_socket(unsigned int );
  unsigned int bluenoc_open_tcp_socket(unsigned int );
  void bluenoc_recv_tcp_beat(unsigned int *, unsigned int , char , char , unsigned int *);
  char bluenoc_send_tcp_beat(unsigned int , char , char , unsigned int *);
}
