// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  RSAPipelineTypes::BIG_INT
// Generated on: Wed Apr 17 15:19:56 EDT 2013
// Bluespec version: 2012.10.beta2 2012-10.10 29674

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<16> to BIG_INT
typedef BitT<16> BIG_INT ;

