// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  All SceMi types
// Generated on: Wed Apr 17 15:19:56 EDT 2013
// Bluespec version: 2012.10.beta2 2012-10.10 29674

#pragma once

#include "PowerStruct.h" 
#include "PowerAssoc.h" 
#include "MemInit.h" 
#include "MemInitLoad.h" 
#include "ProbeControl.h" 
#include "PrbNum.h" 
#include "CosimStruct.h" 
#include "PowerProbe.h" 
#include "PwPrbKind.h" 
#include "Tag.h" 
#include "SimulationControlReq.h" 
#include "SimulationStatusResp.h" 
#include "CreditCount.h" 
#include "CHUNK_T.h" 
#include "BIG_INT.h" 
#include "Addr.h" 
#include "ClkNextRdy.h" 
