// This file automatically generated by SceMiParams::genProbeFile
// DO NOT EDIT
// Generated on: Wed Apr 17 15:19:55 EDT 2013
// Bluespec version: 2012.10.beta2 2012-10.10 29674

#include "bsv_scemi.h"


BSVType *ProbesXactor::createData(unsigned int probeNum, Packet *data, SceMiU64 cycle)
{
  BSVType *type = NULL;
 // No probes are defined!

  return type;
}

unsigned int ProbesXactor::getBitSize(unsigned int probeNum)
{
  return 0;
}

