// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  SceMiXactors::SimulationControlReq
// Generated on: Wed Apr 17 15:19:56 EDT 2013
// Bluespec version: 2012.10.beta2 2012-10.10 29674

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<32> to SimulationControlReq
typedef BitT<32> SimulationControlReq ;

